[workspace]
resolver = "2"
members = ["crates/rom", "crates/n64mem", "crates/oracle", "crates/game", "crates/difftest", "crates/assets", "xtask"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
racer-rom = { path = "crates/rom" }
n64mem = { path = "crates/n64mem" }
oracle = { path = "crates/oracle" }
game = { path = "crates/game" }
assets = { path = "crates/assets" }
sha1 = "0.10"
proptest = "1"
