//! Draft Rust ports from N64Recomp's generated C (`cargo xtask translate`).
//!
//! The output keeps N64Recomp's register-exact semantics and the style of the
//! hand-written ports in `game`: `g[REG]`, `m`, the `game::recomp` helpers,
//! callees through `imports`. It is a draft, not a port: every draft still
//! goes through the per-function loop in CLAUDE.md.
//!
//! Integer code only, for now. Anything else is refused with a reason
//! ([`Refusal`]): floats, FCR31, jump tables, indirect calls, `break`,
//! unaligned and 64-bit accesses.
//!
//! This crate reads the generated C, which is derived from the ROM; neither
//! that C nor translated output is committed. It must not depend on `game`
//! (NOTES.md, "How ports call other functions").

mod c;
mod cfg;
mod emit;
mod ir;
mod structure;

pub use ir::Refusal;

/// A translated function.
pub struct Draft {
    pub name: String,
    /// The function with its doc comment.
    pub source: String,
    /// `use` lines it needs.
    pub uses: String,
    /// Functions it calls, which must be in `game::imports`.
    pub callees: Vec<String>,
    /// False if the control flow was irreducible and came out as a state
    /// machine.
    pub structured: bool,
}

const DOC: &str = "\
`NAME`: TODO: what it does, in one or two sentences.

DRAFT from `cargo xtask translate NAME`, a mechanical translation of
N64Recomp's C. Before it is a port: restructure it, name what registers
hold, document leftovers, domain and QUIRKs, and difftest it.

# Safety
N64Recomp entry point: see [`crate::recomp::enter`].";

/// Translate one generated function (the contents of `generated/NAME.c`).
pub fn translate(src: &str) -> Result<Draft, Refusal> {
    let cfg = cfg::build(src)?;
    let st = structure::structure(&cfg);
    let doc = DOC.replace("NAME", &cfg.name);
    let (source, uses) = emit::function(&cfg.name, &st.body, &doc);
    Ok(Draft {
        name: cfg.name.clone(),
        source,
        uses: emit::use_lines(&uses),
        callees: uses.callees.iter().cloned().collect(),
        structured: st.reducible,
    })
}

/// A module of drafts for swapping in under test (`game`'s `translated`
/// feature): every function that translates, `by_name`, and the refusals.
/// Callees are declared locally, so the module doesn't depend on which
/// symbols `game::imports` lists.
pub fn module(sources: &[(String, String)]) -> String {
    use std::collections::BTreeSet;
    let mut fns = String::new();
    let mut names = Vec::new();
    let mut refused = Vec::new();
    let mut callees = BTreeSet::new();
    for (name, src) in sources {
        match translate(src) {
            Ok(d) => {
                fns.push_str(&d.source);
                fns.push('\n');
                callees.extend(d.callees);
                names.push(d.name);
            }
            Err(r) => refused.push((name.clone(), r.to_string())),
        }
    }
    let mut out = String::from(
        "// Generated by the translate crate from N64Recomp's C. Not committed.\n\
         #[allow(unused_imports)]\n\
         use crate::recomp::*;\n\
         #[allow(unused_imports)]\n\
         use crate::recomp::reg::*;\n\
         use crate::recomp::RecompFn;\n\n\
         #[allow(dead_code)]\n\
         mod imports {\n    pub use crate::imports::runtime;\n    extern \"C\" {\n",
    );
    for c in &callees {
        out.push_str(&format!("        pub fn {c}(rdram: *mut u8, ctx: *mut crate::recomp::RecompContext);\n"));
    }
    out.push_str("    }\n}\n\n");
    out.push_str(&fns);
    out.push_str("/// The draft of `name`, if it translated.\npub fn by_name(name: &str) -> Option<RecompFn> {\n    match name {\n");
    for n in &names {
        out.push_str(&format!("        \"{n}\" => Some({n}),\n"));
    }
    out.push_str("        _ => None,\n    }\n}\n\n/// Functions that didn't translate, and why.\npub const REFUSED: &[(&str, &str)] = &[\n");
    for (n, r) in &refused {
        out.push_str(&format!("    ({n:?}, {r:?}),\n"));
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Hand-written in N64Recomp's style (not from the ROM).
    fn wrap(body: &str) -> String {
        format!(
            "#include \"recomp.h\"\n\nRECOMP_FUNC void func_80001000(uint8_t* rdram, recomp_context* ctx) {{\n    \
             uint64_t hi = 0, lo = 0, result = 0;\n    int c1cs = 0;\n{body}\n;}}\n"
        )
    }

    fn body(src: &str) -> String {
        let d = translate(&wrap(src)).unwrap();
        d.source.lines().filter(|l| !l.starts_with("///")).map(|l| l.trim()).collect::<Vec<_>>().join("\n")
    }

    #[test]
    fn delay_slot_that_clobbers_the_condition_is_saved() {
        let b = body(
            "    // 0x80001000: bne $a0, $at, L_8000100C
    if (ctx->r4 != ctx->r1) {
        // 0x80001004: lui $at, 0x800A
        ctx->r1 = S32(0X800A << 16);
            goto L_8000100C;
    }
    // 0x80001004: lui $at, 0x800A
    ctx->r1 = S32(0X800A << 16);
    // 0x80001008: sw $a1, -0x5D70($at)
    MEM_W(-0X5D70, ctx->r1) = ctx->r5;
L_8000100C:
    // 0x8000100C: jr $ra
    // 0x80001010: nop

    return;",
        );
        assert!(b.contains("let c0 = g[A0] == g[AT];\ng[AT] = li(0x800A_0000);\nif c0 {"), "{b}");
    }

    #[test]
    fn branch_likely_runs_its_delay_slot_only_when_taken() {
        let b = body(
            "L_80001000:
    // 0x80001000: slt $at, $s1, $v0
    ctx->r1 = SIGNED(ctx->r17) < SIGNED(ctx->r2) ? 1 : 0;
    // 0x80001004: bnel $at, $zero, L_80001000
    if (ctx->r1 != 0) {
        // 0x80001008: addiu $s1, $s1, 0x1
        ctx->r17 = ADD32(ctx->r17, 0X1);
            goto L_80001000;
    }
    goto skip_0;
    // 0x80001008: addiu $s1, $s1, 0x1
    ctx->r17 = ADD32(ctx->r17, 0X1);
    skip_0:
    // 0x8000100C: jr $ra
    // 0x80001010: or $s1, $zero, $zero
    ctx->r17 = 0 | 0;
    return;",
        );
        assert!(
            b.contains("loop {\n// L_80001000\ng[AT] = slt(g[S1], g[V0]);\nif g[AT] == 0 {\nbreak;\n}\ng[S1] = addu(g[S1], 1);\n}\ng[S1] = 0;"),
            "{b}"
        );
    }

    #[test]
    fn jal_delay_slot_runs_before_the_call_and_g_is_reborrowed() {
        let d = translate(&wrap(
            "    // 0x80001000: jal 0x80002000
    // 0x80001004: addiu $a0, $zero, 0x4
    ctx->r4 = ADD32(0, 0X4);
    func_80002000(rdram, ctx);
        goto after_0;
    // 0x80001004: addiu $a0, $zero, 0x4
    ctx->r4 = ADD32(0, 0X4);
    after_0:
    // 0x80001008: jr $ra
    // 0x8000100C: or $v1, $v0, $zero
    ctx->r3 = ctx->r2 | 0;
    return;",
        ))
        .unwrap();
        assert!(d.source.contains("g[A0] = 4;\n    call(imports::func_80002000, m, ctx);\n    let g = &mut ctx.gpr;\n    g[V1] = g[V0];"), "{}", d.source);
        assert_eq!(d.callees, ["func_80002000"]);
    }

    #[test]
    fn floats_are_refused() {
        let r = translate(&wrap("    // 0x80001000: lwc1 $f6, 0x0($a0)\n    CHECK_FR(ctx, 6);\n    return;")).err().unwrap();
        assert_eq!(r.kind, "float");
    }
}
