//! Draft Rust ports from N64Recomp's generated C (`cargo xtask translate`).
//!
//! The output keeps N64Recomp's register-exact semantics and the style of the
//! hand-written ports in `game`: `g[REG]`, `m`, the `game::recomp` helpers,
//! callees through `imports`. It is a draft, not a port: every draft still
//! goes through the per-function loop in CLAUDE.md.
//!
//! Integer and float code, jump tables (a `match`, the default calling the
//! runtime's `switch_error`) and `break` (the runtime's `do_break`).
//! Anything else is refused with a reason ([`Refusal`]): indirect calls,
//! unaligned and 64-bit accesses, 64-bit float conversions. Float arithmetic comes out
//! round-to-nearest; conversions take FCR31's rounding bits, kept in a
//! local (NOTES.md, "Floats").
//!
//! This crate reads the generated C, which is derived from the ROM; neither
//! that C nor translated output is committed. It must not depend on `game`
//! (NOTES.md, "How ports call other functions").

mod c;
mod cfg;
mod emit;
mod ir;
mod structure;

pub use ir::Refusal;

/// A translated function.
pub struct Draft {
    pub name: String,
    /// The function with its doc comment.
    pub source: String,
    /// `use` lines it needs.
    pub uses: String,
    /// Functions it calls, which must be in `game::imports`.
    pub callees: Vec<String>,
    /// False if the control flow was irreducible and came out as a state
    /// machine.
    pub structured: bool,
}

const DOC: &str = "\
`NAME`: TODO: what it does, in one or two sentences.

DRAFT from `cargo xtask translate NAME`, a mechanical translation of
N64Recomp's C. Before it is a port: restructure it, name what registers
hold, document leftovers, domain and QUIRKs, and difftest it.

# Safety
N64Recomp entry point: see [`crate::recomp::enter`].";

/// Translate one generated function (the contents of `generated/NAME.c`).
pub fn translate(src: &str) -> Result<Draft, Refusal> {
    let cfg = cfg::build(src)?;
    let st = structure::structure(&cfg);
    let doc = DOC.replace("NAME", &cfg.name);
    let (source, uses) = emit::function(&cfg.name, &st.body, &doc);
    Ok(Draft {
        name: cfg.name.clone(),
        source,
        uses: emit::use_lines(&uses),
        callees: uses.callees.iter().cloned().collect(),
        structured: st.reducible,
    })
}

/// A module of drafts for swapping in under test (`game`'s `translated`
/// feature): every function that translates, `by_name`, and the refusals.
/// Callees are declared locally, so the module doesn't depend on which
/// symbols `game::imports` lists.
pub fn module(sources: &[(String, String)]) -> String {
    use std::collections::BTreeSet;
    let mut fns = String::new();
    let mut names = Vec::new();
    let mut refused = Vec::new();
    let mut callees = BTreeSet::new();
    for (name, src) in sources {
        match translate(src) {
            Ok(d) => {
                fns.push_str(&d.source);
                fns.push('\n');
                callees.extend(d.callees);
                names.push(d.name);
            }
            Err(r) => refused.push((name.clone(), r.to_string())),
        }
    }
    let mut out = String::from(
        "// Generated by the translate crate from N64Recomp's C. Not committed.\n\
         #[allow(unused_imports)]\n\
         use crate::recomp::*;\n\
         #[allow(unused_imports)]\n\
         use crate::recomp::reg::*;\n\
         use crate::recomp::RecompFn;\n\n\
         #[allow(dead_code)]\n\
         mod imports {\n    pub use crate::imports::runtime;\n    extern \"C\" {\n",
    );
    for c in &callees {
        out.push_str(&format!("        pub fn {c}(rdram: *mut u8, ctx: *mut crate::recomp::RecompContext);\n"));
    }
    out.push_str("    }\n}\n\n");
    out.push_str(&fns);
    out.push_str("/// The draft of `name`, if it translated.\npub fn by_name(name: &str) -> Option<RecompFn> {\n    match name {\n");
    for n in &names {
        out.push_str(&format!("        \"{n}\" => Some({n}),\n"));
    }
    out.push_str("        _ => None,\n    }\n}\n\n/// Functions that didn't translate, and why.\npub const REFUSED: &[(&str, &str)] = &[\n");
    for (n, r) in &refused {
        out.push_str(&format!("    ({n:?}, {r:?}),\n"));
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Hand-written in N64Recomp's style (not from the ROM).
    fn wrap(body: &str) -> String {
        format!(
            "#include \"recomp.h\"\n\nRECOMP_FUNC void func_80001000(uint8_t* rdram, recomp_context* ctx) {{\n    \
             uint64_t hi = 0, lo = 0, result = 0;\n    int c1cs = 0;\n{body}\n;}}\n"
        )
    }

    fn body(src: &str) -> String {
        let d = translate(&wrap(src)).unwrap();
        d.source.lines().filter(|l| !l.starts_with("///")).map(|l| l.trim()).collect::<Vec<_>>().join("\n")
    }

    #[test]
    fn delay_slot_that_clobbers_the_condition_is_saved() {
        let b = body(
            "    // 0x80001000: bne $a0, $at, L_8000100C
    if (ctx->r4 != ctx->r1) {
        // 0x80001004: lui $at, 0x800A
        ctx->r1 = S32(0X800A << 16);
            goto L_8000100C;
    }
    // 0x80001004: lui $at, 0x800A
    ctx->r1 = S32(0X800A << 16);
    // 0x80001008: sw $a1, -0x5D70($at)
    MEM_W(-0X5D70, ctx->r1) = ctx->r5;
L_8000100C:
    // 0x8000100C: jr $ra
    // 0x80001010: nop

    return;",
        );
        assert!(b.contains("let c0 = g[A0] == g[AT];\ng[AT] = li(0x800A_0000);\nif c0 {"), "{b}");
    }

    #[test]
    fn branch_likely_runs_its_delay_slot_only_when_taken() {
        let b = body(
            "L_80001000:
    // 0x80001000: slt $at, $s1, $v0
    ctx->r1 = SIGNED(ctx->r17) < SIGNED(ctx->r2) ? 1 : 0;
    // 0x80001004: bnel $at, $zero, L_80001000
    if (ctx->r1 != 0) {
        // 0x80001008: addiu $s1, $s1, 0x1
        ctx->r17 = ADD32(ctx->r17, 0X1);
            goto L_80001000;
    }
    goto skip_0;
    // 0x80001008: addiu $s1, $s1, 0x1
    ctx->r17 = ADD32(ctx->r17, 0X1);
    skip_0:
    // 0x8000100C: jr $ra
    // 0x80001010: or $s1, $zero, $zero
    ctx->r17 = 0 | 0;
    return;",
        );
        assert!(
            b.contains("loop {\n// L_80001000\ng[AT] = slt(g[S1], g[V0]);\nif g[AT] == 0 {\nbreak;\n}\ng[S1] = addu(g[S1], 1);\n}\ng[S1] = 0;"),
            "{b}"
        );
    }

    /// Two loops sharing a header (inner latch `bne`, outer latch `bnel`
    /// with a delay slot): the outer latch's path must stay inside the loop.
    /// A trailing `continue` there is implicit, so hoisting that path out of
    /// the loop as its "exit" would make it fall off the end (session 8:
    /// func_80034650's draft ran one row).
    #[test]
    fn shared_loop_header_keeps_the_outer_latch_inside() {
        let b = body(
            "L_80001000:
    // 0x80001000: addiu $a0, $a0, 0x1
    ctx->r4 = ADD32(ctx->r4, 0X1);
    // 0x80001004: bne $a0, $a1, L_80001000
    if (ctx->r4 != ctx->r5) {
        // 0x80001008: nop

            goto L_80001000;
    }
    // 0x80001008: nop

    // 0x8000100C: addiu $a2, $a2, 0x1
    ctx->r6 = ADD32(ctx->r6, 0X1);
    // 0x80001010: bnel $a2, $a3, L_80001000
    if (ctx->r6 != ctx->r7) {
        // 0x80001014: or $a0, $zero, $zero
        ctx->r4 = 0 | 0;
            goto L_80001000;
    }
    goto skip_0;
    // 0x80001014: or $a0, $zero, $zero
    ctx->r4 = 0 | 0;
    skip_0:
    // 0x80001018: jr $ra
    // 0x8000101C: nop

    return;",
        );
        // After the outer increment: return, or reset a0 and go round again.
        let tail = &b[b.find("g[A2] = addu(g[A2], 1);").expect(&b)..];
        assert!(tail.contains("g[A0] = 0;\n}\n}"), "the outer latch left the loop:\n{b}");
    }

    /// A label right before a branch (L_8000101C): its block starts at the
    /// branch. It used to keep the previous instruction's address, so its
    /// label collided with L_80001018's, and the `bnel` path's jump to it
    /// bound to L_80001018 and ran the `+ 0x10` (session 9: 18 drafts had
    /// such a collision, func_8003FDCC's harmlessly).
    #[test]
    fn label_before_a_branch_gets_its_own_name() {
        let b = body(
            "    // 0x80001000: blez $t1, L_80001018
    if (SIGNED(ctx->r9) <= 0) {
        // 0x80001004: or $a1, $zero, $zero
        ctx->r5 = 0 | 0;
            goto L_80001018;
    }
    // 0x80001004: or $a1, $zero, $zero
    ctx->r5 = 0 | 0;
    // 0x80001008: bnel $t2, $zero, L_8000101C
    if (ctx->r10 != 0) {
        // 0x8000100C: addiu $a2, $a2, 0x1
        ctx->r6 = ADD32(ctx->r6, 0X1);
            goto L_8000101C;
    }
    goto skip_0;
    // 0x8000100C: addiu $a2, $a2, 0x1
    ctx->r6 = ADD32(ctx->r6, 0X1);
    skip_0:
    // 0x80001010: addiu $a1, $a1, 0x1
    ctx->r5 = ADD32(ctx->r5, 0X1);
L_80001018:
    // 0x80001018: addiu $a2, $a2, 0x10
    ctx->r6 = ADD32(ctx->r6, 0X10);
L_8000101C:
    // 0x8000101C: bne $a2, $zero, L_80001028
    if (ctx->r6 != 0) {
        // 0x80001020: nop

            goto L_80001028;
    }
    // 0x80001020: nop

    // 0x80001024: or $v0, $a1, $zero
    ctx->r2 = ctx->r5 | 0;
L_80001028:
    // 0x80001028: jr $ra
    // 0x8000102C: nop

    return;",
        );
        assert!(b.contains("'b_8000101C: {"), "{b}");
        assert!(!b.contains("'b_80001018: {\n'b_80001018: {"), "{b}");
        // The bnel path: a2 += 1, then straight to L_8000101C.
        assert!(b.contains("g[A2] = addu(g[A2], 1);\nbreak 'b_8000101C;"), "{b}");
    }

    #[test]
    fn jal_delay_slot_runs_before_the_call_and_g_is_reborrowed() {
        let d = translate(&wrap(
            "    // 0x80001000: jal 0x80002000
    // 0x80001004: addiu $a0, $zero, 0x4
    ctx->r4 = ADD32(0, 0X4);
    func_80002000(rdram, ctx);
        goto after_0;
    // 0x80001004: addiu $a0, $zero, 0x4
    ctx->r4 = ADD32(0, 0X4);
    after_0:
    // 0x80001008: jr $ra
    // 0x8000100C: or $v1, $v0, $zero
    ctx->r3 = ctx->r2 | 0;
    return;",
        ))
        .unwrap();
        assert!(d.source.contains("g[A0] = 4;\n    call(imports::func_80002000, m, ctx);\n    let g = &mut ctx.gpr;\n    g[V1] = g[V0];"), "{}", d.source);
        assert_eq!(d.callees, ["func_80002000"]);
    }

    /// A jump table as N64Recomp prints it, with a delay slot that does
    /// something: it runs before the match, and its dead copy after the
    /// switch runs only if `switch_error` returns. Cases 1 and 2 share a
    /// target.
    #[test]
    fn jump_table_becomes_a_match() {
        let b = body(
            "    // 0x80001000: sll         $t6, $a0, 2
    ctx->r14 = S32(ctx->r4 << 2);
    // 0x80001004: lui         $at, 0x800B
    ctx->r1 = S32(0X800B << 16);
    // 0x80001008: addu        $at, $at, $t6
    gpr jr_addend_80001010 = ctx->r14;
    ctx->r1 = ADD32(ctx->r1, ctx->r14);
    // 0x8000100C: lw          $t6, -0x7E00($at)
    ctx->r14 = ADD32(ctx->r1, -0X7E00);
    // 0x80001010: jr          $t6
    // 0x80001014: addiu       $v1, $zero, 0x7
    ctx->r3 = ADD32(0, 0X7);

    switch (jr_addend_80001010 >> 2) {
        case 0: goto L_80001018; break;
        case 1: goto L_80001020; break;
        case 2: goto L_80001020; break;
        default: switch_error(__func__, 0x80001010, 0x800A8200);
    }
    // 0x80001014: addiu       $v1, $zero, 0x7
    ctx->r3 = ADD32(0, 0X7);
L_80001018:
    // 0x80001018: jr          $ra
    // 0x8000101C: addiu       $v0, $zero, 0x1
    ctx->r2 = ADD32(0, 0X1);
    return;
    // 0x8000101C: addiu       $v0, $zero, 0x1
    ctx->r2 = ADD32(0, 0X1);
L_80001020:
    // 0x80001020: jr          $ra
    // 0x80001024: addiu       $v0, $zero, 0x2
    ctx->r2 = ADD32(0, 0X2);
    return;",
        );
        let want = "let jr_addend_80001010 = g[T6];\ng[AT] = addu(g[AT], g[T6]);\ng[T6] = addu(g[AT], (-0x7E00i64) as u64);\n\
                    g[V1] = 7;\nmatch jr_addend_80001010 >> 2 {\n0 => {\nbreak 'b_8000101C;\n}\n1 | 2 => {}\n\
                    _ => {\nimports::runtime::switch_error(c\"func_80001000\".as_ptr(), 0x8000_1010, 0x800A_8200);\ng[V1] = 7;\n\
                    break 'b_8000101C;\n}\n}\n// L_80001020\ng[V0] = 2;\nreturn;\n}\n// L_80001018\ng[V0] = 1;";
        assert!(b.contains(want), "{b}");
    }

    #[test]
    fn jump_table_shapes_are_checked() {
        let sw = |cases: &str| {
            wrap(&format!(
                "    // 0x80001000: addu        $at, $at, $t6
    gpr jr_addend_80001008 = ctx->r14;
    ctx->r1 = ADD32(ctx->r1, ctx->r14);
    // 0x80001008: jr          $t6
    switch (jr_addend_80001008 >> 2) {{
{cases}
    }}
L_80001010:
    return;"
            ))
        };
        let ok = "        case 0: goto L_80001010; break;\n        default: switch_error(__func__, 0x80001008, 0x800A8200);";
        assert!(translate(&sw(ok)).is_ok());
        for bad in [
            // cases out of order
            "        case 1: goto L_80001010; break;\n        default: switch_error(__func__, 0x80001008, 0x800A8200);",
            // no default
            "        case 0: goto L_80001010; break;",
            // a default for another jr
            "        case 0: goto L_80001010; break;\n        default: switch_error(__func__, 0x80001004, 0x800A8200);",
            // anything else inside
            "        case 0: goto L_80001010; break;\n    ctx->r1 = 0 | 0;\n        default: switch_error(__func__, 0x80001008, 0x800A8200);",
        ] {
            assert_eq!(translate(&sw(bad)).err().map(|r| r.kind), Some("jump table"), "{bad}");
        }
    }

    /// IDO's divide-by-zero guard: `do_break` becomes the runtime hook, and
    /// the code after it still runs if it returns.
    #[test]
    fn break_calls_the_runtime() {
        let b = body(
            "    // 0x80001000: bne         $t1, $zero, L_8000100C
    if (ctx->r9 != 0) {
        // 0x80001004: nop

            goto L_8000100C;
    }
    // 0x80001004: nop

    // 0x80001008: break       7
    do_break(2147487752);
L_8000100C:
    // 0x8000100C: jr          $ra
    // 0x80001010: addiu       $v0, $zero, 0x1
    ctx->r2 = ADD32(0, 0X1);
    return;",
        );
        assert!(b.contains("if g[T1] == 0 {\nimports::runtime::do_break(0x8000_1008);\n}\n// L_8000100C\ng[V0] = 1;"), "{b}");
    }

    #[test]
    fn long_conversions_are_refused() {
        let r = translate(&wrap("    // 0x80001000: cvt.l.s $f0, $f2\n    ctx->f0.u64 = CVT_L_S(ctx->f2.fl);\n    return;")).err().unwrap();
        assert_eq!(r.kind, "float");
    }

    #[test]
    fn float_ops_use_fpr_accessors_and_c1cs() {
        let b = body(
            "    // 0x80001000: lwc1 $f4, 0x0($a0)
    CHECK_FR(ctx, 4);
    ctx->f4.u32l = MEM_W(ctx->r4, 0X0);
    // 0x80001004: c.lt.s $f4, $f12
    CHECK_FR(ctx, 4);
    CHECK_FR(ctx, 12);
    c1cs = ctx->f4.fl < ctx->f12.fl;
    // 0x80001008: bc1f L_80001014
    if (!c1cs) {
        // 0x8000100C: mul.s $f0, $f4, $f4
        CHECK_FR(ctx, 0);
        NAN_CHECK(ctx->f4.fl); NAN_CHECK(ctx->f4.fl);
        ctx->f0.fl = MUL_S(ctx->f4.fl, ctx->f4.fl);
            goto L_80001014;
    }
    // 0x8000100C: mul.s $f0, $f4, $f4
    CHECK_FR(ctx, 0);
    NAN_CHECK(ctx->f4.fl); NAN_CHECK(ctx->f4.fl);
    ctx->f0.fl = MUL_S(ctx->f4.fl, ctx->f4.fl);
    // 0x80001010: trunc.w.s $f2, $f0
    ctx->f2.u32l = TRUNC_W_S(ctx->f0.fl);
L_80001014:
    // 0x80001014: jr $ra
    // 0x80001018: nop

    return;",
        );
        let want = "let mut c1cs = false;\nctx.fpr[4].set_u32l(lw(m, g[A0], 0) as u32);\n\
                    c1cs = ctx.fpr[4].fl() < ctx.fpr[12].fl();\nctx.fpr[0].set_fl(ctx.fpr[4].fl() * ctx.fpr[4].fl());\n\
                    if c1cs {\nctx.fpr[2].set_u32l(fpu::trunc_w_s(ctx.fpr[0].fl()));\n}";
        assert!(b.contains(want), "{b}");
    }
}
